name: csc_picker_i18n
description: '[i18n support] A flutter package to display list of Countries, States and Cities depends on Selected, also you can search country, state, and city all around the world.'
version: 0.2.8
homepage: https://github.com/dmi3coder/csc_picker_i18n

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - lib/assets/
